### PR TITLE
sleepOnBlur + sleepOnBlurTimeout

### PR DESCRIPTION
**Pull request by r3wt**
@joewalnes 

I added these methods. i haven't tested it yet but i'm about to. Comments/Suggestions welcomed

### CODE REVIEW

**Comment by r3wt** [comment]
hmm, apparently status code 1001 can't be set?

**Comment by r3wt** [comment]
img

**Comment by r3wt** [comment]
todo: possibly add event emission for onblur/onfocus?

**Comment by agalazis** [comment]
I thinl that this  functionality doen't need to be  included in the core library as usually you wouldn't kill a connection on blur. Ofcourse you can make a tiny one that complements reconnecting websocket and make it available to the people who need it, any other opinions ? (github needs a voting facility I think :p )
maybe post hands to vote(don't take it personally this is opinionated- but we need to find out if people would actually need/use this feature):
:-1:

**Comment by agalazis** [comment]
Disregard my prevous post I just realised that you are actually stopping reconnects on blur tha might be usefull sorry and thanks fro bringin it up.

**Comment by r3wt** [comment]
@agalazis this is about maximizing performance at scale really. say you have 10,000 connected clients, and 5,000 of them are idle connections with the browser window out of focus. wouldn't it be optimal to just disconnect those people until they refocus the window? i think so

**Comment by agalazis** [comment]
Yes just misinterpreted the point of this commit until i read the code, sorry for that.

**Comment by r3wt** [comment]
@agalazis thats why the behavior is disabled by default

**Comment by r3wt** [comment]
This pull causes bugs in IE. i'm closing it.

**Pull request closed without merging**
